import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "./providers";
import { ModalsProvider } from "@/components/modals/modals-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <html
          lang="en"
          data-new-gr-c-s-check-loaded="14.1223.0"
          data-gr-ext-installed=""
        >
          <body>
            {children}
            <Toaster />
            <ModalsProvider />
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
